apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 for "admin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 for "password"