apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: shoppingapi.azurecr.io/shoppingapi:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-url
                  key: CONNECTION_STRING
            - name: DatabaseSettings__DatabaseName
              value: "mongodb"
            - name: DatabaseSettings__CollectionName
              value: "Products"
            # - name: ASPNETCORE_URLS
            #   value: "http://+:5555"
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 80
      
      # targetPort: 5555