apiVersion : apps/v1
kind: Deployment
metadata:
  name: shoppingapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi 
    spec:
      containers:
        - name: shoppingapi 
          image: shoppingapi.azurecr.io/shoppingapi
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: shoppingapi
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: shoppingapi