# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Shoppingonline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3b5862927e754dbb9fb46e3272e12297 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c92f7591edbd4c3792c993e84835999c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Shopping.Client/Dockerfile
        push: true
        tags: khoalv26/newshoppingonline:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Shoppingonline'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d78000c681f04897a8d9b111e370711e }}
        images: 'khoalv26/newshoppingonline:latest'